<?php

// ------------------------------------------------------------------------- //
// Enterprise-X for Xoops //
// Version: 1.0 //
// ------------------------------------------------------------------------- //
// Author: Wang Jue (alias wjue)  //
// Purpose: Professional Corporate Presentation Application //
// email: wjue@wjue.org  //
// URLs: http://www.wjue.org, http://www.guanxiCRM.com //
// Copyright 2004 (c): Wang Jue  //
// Graphic design: (c) www.Imagocn.net  //
// You may not change or alter any portion of this comment or credits //
// of supporting developers from this source code or any supporting //
// source code which is considered copyrighted (c) material of the //
// original comment or credit authors.  //
//---------------------------------------------------------------------------//
// This program is free software; you can redistribute it and/or modify //
// it under the terms of the GNU General Public License as published by //
// the Free Software Foundation; either version 2 of the License, or //
// (at your option) any later version.  //
//   //
// This program is distributed in the hope that it will be useful, //
// but WITHOUT ANY WARRANTY; without even the implied warranty of //
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the //
// GNU General Public License for more details. //
//---------------------------------------------------------------------------//
$modversion['name'] = 'Enterprise-X';
$modversion['version'] = 1.0;
$modversion['description'] = 'To professionally present your enterprise';
$modversion['credits'] = 'Copyright(c) 2004, wjue (Wang Jue) http://www.wjue.org, http://www.guanxiCRM.com';
$modversion['help'] = 'enterprise.html';
$modversion['license'] = 'GPL see LICENSE';
$modversion['official'] = 1;
$modversion['image'] = 'enterprise-x.png';
$modversion['dirname'] = 'enterprise';
// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = 'sql/mysql.sql';
//$modversion['sqlfile']['postgresql'] = "sql/pgsql.sql";
// Tables created by sql file (without prefix!)
$modversion['tables'][0] = 'enterprise_front';
$modversion['tables'][1] = 'enterprise_aboutus';
$modversion['tables'][2] = 'enterprise_service';
$modversion['tables'][3] = 'enterprise_success_story';
$modversion['tables'][4] = 'enterprise_success_story_family';
// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = 'admin/index.php';
//$modversion['adminmenu'] = "admin/menu.php";
// Templates
$modversion['templates'][1]['file'] = 'enterprise_index.html';
$modversion['templates'][1]['description'] = '';
$modversion['templates'][2]['file'] = 'enterprise_aboutus.html';
$modversion['templates'][2]['description'] = '';
$modversion['templates'][3]['file'] = 'enterprise_services.html';
$modversion['templates'][3]['description'] = '';
$modversion['templates'][4]['file'] = 'enterprise_service.html';
$modversion['templates'][4]['description'] = '';
$modversion['templates'][5]['file'] = 'enterprise_testimonies.html';
$modversion['templates'][5]['description'] = '';
$modversion['templates'][6]['file'] = 'enterprise_testimony.html';
$modversion['templates'][6]['description'] = '';
$modversion['templates'][7]['file'] = 'enterprise_adminmenu.html';
$modversion['templates'][7]['description'] = '';
$modversion['templates'][8]['file'] = 'e_front_form.html';
$modversion['templates'][8]['description'] = '';
$modversion['templates'][9]['file'] = 'e_servicelist.html';
$modversion['templates'][9]['description'] = '';
$modversion['templates'][10]['file'] = 'e_service_form.html';
$modversion['templates'][10]['description'] = '';
$modversion['templates'][11]['file'] = 'e_aboutuslist.html';
$modversion['templates'][11]['description'] = '';
$modversion['templates'][12]['file'] = 'e_aboutus_form.html';
$modversion['templates'][12]['description'] = '';
$modversion['templates'][13]['file'] = 'e_caselist.html';
$modversion['templates'][13]['description'] = '';
$modversion['templates'][14]['file'] = 'e_case_form.html';
$modversion['templates'][14]['description'] = '';
$modversion['templates'][15]['file'] = 'e_casecat_form.html';
$modversion['templates'][15]['description'] = '';
$modversion['templates'][16]['file'] = 'e_catedit_form.html';
$modversion['templates'][16]['description'] = '';
$modversion['templates'][17]['file'] = 'e_reallydeletecat.html';
$modversion['templates'][17]['description'] = '';
// Menu
$modversion['hasMain'] = 1;
$modversion['sub'][1]['name'] = 'About Us';
$modversion['sub'][1]['url'] = 'aboutus.php';
$modversion['sub'][2]['name'] = 'Services';
$modversion['sub'][2]['url'] = 'services.php';
$modversion['sub'][3]['name'] = 'Success Stories';
$modversion['sub'][3]['url'] = 'testimonies.php';
// Search
//$modversion['hasSearch'] = 1;
//$modversion['search']['file'] = "include/search.inc.php";
//$modversion['search']['func'] = "enterprise_search";
